export const ADD_TRANSACTION = "ADD_TRANSACTION";
export const REMOVE_TRANSACTION = "REMOVE_TRANSACTION";
export const INCREMENT_PLN = "INCREMENT_PLN";
export const DECREMENT_PLN = "DECREMENT_PLN";
export const CHANGE_PLN_RATE = "CHANGE_PLN_RATE";
